### ISSUE TITLE
单点登录(sso)与oauth2 - 十一郎的博客

### ISSUE THREAD

**Issue by xiaoshiyi123** [xiaoshiyi123/blog_comments#2]
http://xiaoshiyi.top/2019/12/15/sso/ 

 记录和分享,

**Comment by yugecxy** [comment]
傻逼

**Comment by yugecxy** [comment]
楼主，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼，牛逼！
